### ISSUE TITLE
Add ability to override time out environment variable CF_DIAL_TIMEOUT

### ISSUE THREAD

**Issue by kchouhan** [concourse/cf-resource#37] opened 2017-10-05 08:55 UTC
I have a single VM installation of Concourse. I am not able to login to cf with default timeout of 5s. When I setup the environment variable CF_DIAL_TIMEOUT to 20, it works.

This works on my VM but my Concourse job still fails. Is there a way to override this environment variable value at resource declaration?

**Comment by MarkKropf** [comment] 2017-10-06 01:03
I just ran into the same problem where we were getting timeouts on a new concourse deployment and setting this in the container caused the push to function. I saw this on both concourse 3.4.1 & 3.50 against PWS

@xoebus  fyi, this is what caused the issue I spoke to you about today.

**Comment by goehmen** [comment] 2017-10-27 17:37
I ran into this issue w/3.4.1 & 3.5.0 and used @DaxterM 's custom resource as a workaround.

I just upgraded to 3.6.0 & can confirm that the issue is fixed with the cf resource.  @MarkKropf @jama-pivotal

**Comment by vito** [comment] 2017-11-29 01:16
this was fixed by https://github.com/concourse/cf-resource/pull/33

**Closed by vito** 2017-11-29 01:16 UTC
