### ISSUE TITLE
bluemix authentication failure

### ISSUE THREAD

**Issue by frank-long** [concourse/cf-resource#32] opened 2017-07-11 09:30 UTC
I can't authenticate with bluemix using this resource. Not sure if it happened since taking the latest concourse upgrade 3.2.1, or if it's something on the bluemix side that has changed.

A manual cli cf login works, but a manual cli cf auth fails

https://stackoverflow.com/questions/45029574/concourse-cf-resource-bluemix-authentication

As per my comment above this looks like an issue with version 6.2.7 of the cf cli, 6.2.8 works fine.

**Comment by jtarchie** [comment] 2017-07-11 13:12
@frank-long, can you confirm what version of concourse you are? It looks like the resource did get updated to the latest CLI at some point.

**Comment by frank-long** [comment] 2017-07-11 14:08
Hi, I'm using v3.2.1 of concourse. The "put" container says it's using v6.2.7 of the cf cli app.  I installed v6.2.7 cf cli locally and was was able to reproduce the problem on my mac.

**Comment by jtarchie** [comment] 2017-07-17 21:57
@frank-long, please update your concourse and confirm this is no longer an issue. Thanks!

**Comment by jenspinney** [comment] 2017-08-16 18:00
@jtarchie I'm seeing the same problem with the latest version of concourse. The cf CLI version is 6.29.0, and I was able to reproduce the problem when using that CLI version on my mac as well. Similar to what @frank-long said, `cf login` works fine, but `cf auth` doesn't. If I use cf CLI 6.26, the problem doesn't exist. It looks like [the fix](https://github.com/cloudfoundry/cli/commit/55b2766c6419ba00cc412035b052826b4b957fec) won't be available until v6.30, which doesn't exist yet.

**Comment by jtarchie** [comment] 2017-08-25 15:05
@jenspinney, we update always to the latest CLI, looks like v6.30 hasn't been released yet.

**Comment by jtarchie** [comment] 2017-08-29 16:10
Since our CI automatically pulls in the latest. I'm going to close this as it seems to be version related. When the new cf cli does get releases, please test it out and let us know if it works.

**Closed by jtarchie** 2017-08-29 16:10 UTC
